services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Divante\ObjectMapperBundle\Service\MapperService:
      public: true

    Divante\ObjectMapperBundle\Mapper\MapperContextInterface:
      class: Divante\ObjectMapperBundle\Mapper\MapperContext

    Divante\ObjectMapperBundle\Mapper\Strategy\MapBoolValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapDateValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapStructuredValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapMultiObjectValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapObjectValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapQuantityValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapSelectValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapTextareaValue:
      tags:
          - {name: object_mapper.mapStrategy}
    Divante\ObjectMapperBundle\Mapper\Strategy\MapWysiwygValue:
      tags:
      - {name: object_mapper.mapStrategy}
    Divante\ObjectMapperBundle\Mapper\Strategy\MapTextValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapUserValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Controller\:
       resource: '../../Controller'
       public: true
       tags: ['controller.service_arguments']

    Divante\MagentoIntegrationBundle\Interfaces\MapperInterface: '@Divante\ObjectMapperBundle\Service\MapperService'

    Divante\ObjectMapperBundle\Mapper\Strategy\MapMultiSelectValue:
      tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapBlockValue:
        tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapObjectBricks:
        tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\MapClassificationStoreValue:
        tags:
          - {name: object_mapper.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapBooleanKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapCheckboxKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapQuantityValueKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapSelectKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapTextKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapCountrySelectKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapLanguageSelectKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapDateKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}

    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapTextAreaKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}
    Divante\ObjectMapperBundle\Mapper\Strategy\ClassificationStore\MapWysiwygKey:
        tags:
          - {name: object_mapper_classificationstore.mapStrategy}
